### model
model_name_or_path: ./Qwen2.5-7B-Instruct  
#trust_remote_code: true
quantization_bit: 4  # 4-bit量化节省显存
quantization_method: bnb  # 使用bitsandbytes
template: qwen

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: q_proj,v_proj,k_proj,o_proj,gate_proj,up_proj,down_proj  

### dataset
dataset: medical_llm #这里填注册名二补数数据名 
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2.5-7b-medical
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### ktransformers
use_kt: false  # 对于 ChatGLM3-6B，建议先关闭 KTransformers
# kt_optimize_rule: examples/kt_optimize_rules/DeepSeek-V2-Lite-Chat-sft-amx.yaml
# cpu_infer: 32
# chunk_size: 8192

### eval
# eval_dataset: alpaca_en_demo
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
